changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Data sources and research
      labels:
        - data-source
        - research
    - title: Documentation and community
      labels:
        - documentation
        - community
    - title: Other changes
      labels:
        - "*"
